"""
TRON Agent for Aurora Sun V1.

Main security automation agent:
- 3 operating modes (Observe, Suggest+Auto-Low, Auto-High)
- Coordinates threat monitor, compliance auditor, and incident graph
- Crisis override: Mental Health > Security (defer to CrisisService)
- Every action -> DM to admin

Reference: ARCHITECTURE.md Section 7 (TRON Agent)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from .compliance import ComplianceAuditor
from .incident import IncidentGraph, IncidentSeverity
from .threat_monitor import ActiveThreat, ThreatLevel, ThreatMonitor, ThreatScore

logger = logging.getLogger(__name__)


# =============================================================================
# Enums
# =============================================================================


class TRONMode(StrEnum):
    """TRON operating modes.

    OBSERVE: Monitor only, log everything, alert admin (dev/default)
    SUGGEST_AUTO_LOW: Auto-handle LOW threats, suggest for MEDIUM+
    AUTO_HIGH: Auto-handle up to HIGH, alert for CRITICAL only
    """

    OBSERVE = "observe"
    SUGGEST_AUTO_LOW = "suggest_auto_low"
    AUTO_HIGH = "auto_high"


# =============================================================================
# Security Report
# =============================================================================


@dataclass
class SecurityReport:
    """Security status report generated by TRON.

    Attributes:
        generated_at: When the report was generated.
        mode: Current TRON operating mode.
        active_threats: Number of active threats.
        threat_breakdown: Threats by level.
        open_incidents: Number of open incidents.
        compliance_status: Latest compliance report status.
        recent_threats: Most recent threats.
        recent_incidents: Most recent incidents.
        recommendations: Suggested actions.
    """

    generated_at: datetime
    mode: str
    active_threats: int
    threat_breakdown: dict[str, int] = field(default_factory=dict)
    open_incidents: int = 0
    compliance_status: str = "unknown"
    recent_threats: list[dict[str, Any]] = field(default_factory=list)
    recent_incidents: list[dict[str, Any]] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)


# =============================================================================
# TRON Agent
# =============================================================================


class TRONAgent:
    """Security Automation Agent.

    Default mode: OBSERVE. Every action reported to admin.
    Crisis override: Mental Health > Security.

    Usage:
        tron = TRONAgent(mode=TRONMode.OBSERVE)

        # Scan for threats
        threats = await tron.scan(user_id=1, event_type="message", details={})

        # Assess specific user
        score = tron.assess_threat(user_id=1)

        # Get security report
        report = await tron.get_security_report()
    """

    # Auto-action thresholds per mode
    AUTO_ACTION_LEVELS: dict[TRONMode, set[ThreatLevel]] = {
        TRONMode.OBSERVE: set(),  # No auto actions
        TRONMode.SUGGEST_AUTO_LOW: {ThreatLevel.LOW},
        TRONMode.AUTO_HIGH: {ThreatLevel.LOW, ThreatLevel.MEDIUM, ThreatLevel.HIGH},
    }

    def __init__(
        self,
        mode: TRONMode = TRONMode.OBSERVE,
        admin_chat_id: int | None = None,
    ) -> None:
        """Initialize TRON agent.

        Args:
            mode: Operating mode.
            admin_chat_id: Telegram chat ID for admin notifications.
        """
        self._mode = mode
        self._admin_chat_id = admin_chat_id
        self._threat_monitor = ThreatMonitor()
        self._compliance = ComplianceAuditor()
        self._incidents = IncidentGraph()
        self._crisis_active: bool = False

        logger.info("tron_agent_initialized mode=%s", mode.value)

    @property
    def mode(self) -> TRONMode:
        """Current operating mode."""
        return self._mode

    @mode.setter
    def mode(self, value: TRONMode) -> None:
        """Set operating mode.

        Args:
            value: New mode.
        """
        old_mode = self._mode
        self._mode = value
        logger.info(
            "tron_mode_changed from=%s to=%s",
            old_mode.value,
            value.value,
        )

    @property
    def threat_monitor(self) -> ThreatMonitor:
        """Access the threat monitor."""
        return self._threat_monitor

    @property
    def compliance(self) -> ComplianceAuditor:
        """Access the compliance auditor."""
        return self._compliance

    @property
    def incidents(self) -> IncidentGraph:
        """Access the incident graph."""
        return self._incidents

    @property
    def crisis_active(self) -> bool:
        """Whether a crisis override is active."""
        return self._crisis_active

    def set_crisis_override(self, active: bool) -> None:
        """Set crisis override flag.

        When active, TRON defers security actions to CrisisService.
        Mental Health > Security.

        Args:
            active: Whether crisis override should be active.
        """
        self._crisis_active = active
        if active:
            logger.warning("tron_crisis_override_active security_deferred")
        else:
            logger.info("tron_crisis_override_cleared")

    # -------------------------------------------------------------------------
    # Core Methods
    # -------------------------------------------------------------------------

    async def scan(
        self,
        user_id: int | None = None,
        event_type: str = "",
        details: dict[str, str | int | float | bool | None] | None = None,
    ) -> list[ActiveThreat]:
        """Scan an event for threats and handle according to mode.

        Args:
            user_id: User who triggered the event.
            event_type: Type of event.
            details: Additional event details.

        Returns:
            List of detected threats.
        """
        if details is None:
            details = {}

        # Crisis override: skip security enforcement
        if self._crisis_active:
            logger.debug("tron_scan_skipped crisis_override_active")
            return []

        # Detect threats
        threats = self._threat_monitor.detect_anomalies(
            user_id=user_id,
            event_type=event_type,
            details=details,
        )

        # Handle threats based on mode
        for threat in threats:
            await self._handle_threat(threat)

        return threats

    async def _handle_threat(self, threat: ActiveThreat) -> None:
        """Handle a detected threat based on current mode.

        Args:
            threat: The detected threat.
        """
        auto_levels = self.AUTO_ACTION_LEVELS.get(self._mode, set())

        if threat.level in auto_levels:
            # Auto-handle: create incident and process
            await self._incidents.handle_incident(
                title=f"Auto-handled: {threat.threat_type}",
                description=threat.description,
                severity=self._threat_to_incident_severity(threat.level),
                threat_id=threat.threat_id,
                user_id=threat.user_id,
            )
            logger.info(
                "tron_auto_handled threat=%s level=%s",
                threat.threat_id,
                threat.level.value,
            )
        else:
            # Observe/suggest: log incident for admin review
            await self._incidents.log_incident(
                title=f"[{self._mode.value}] {threat.threat_type}",
                description=threat.description,
                severity=self._threat_to_incident_severity(threat.level),
            )
            logger.info(
                "tron_threat_logged_for_review threat=%s level=%s mode=%s",
                threat.threat_id,
                threat.level.value,
                self._mode.value,
            )

    def _threat_to_incident_severity(self, level: ThreatLevel) -> IncidentSeverity:
        """Map threat level to incident severity.

        Args:
            level: Threat level.

        Returns:
            Corresponding incident severity.
        """
        mapping: dict[ThreatLevel, IncidentSeverity] = {
            ThreatLevel.NONE: IncidentSeverity.LOW,
            ThreatLevel.LOW: IncidentSeverity.LOW,
            ThreatLevel.MEDIUM: IncidentSeverity.MEDIUM,
            ThreatLevel.HIGH: IncidentSeverity.HIGH,
            ThreatLevel.CRITICAL: IncidentSeverity.CRITICAL,
        }
        return mapping.get(level, IncidentSeverity.LOW)

    def assess_threat(self, user_id: int) -> ThreatScore:
        """Assess current threat level for a specific user.

        Args:
            user_id: User to assess.

        Returns:
            ThreatScore with numeric score and level.
        """
        return self._threat_monitor.calculate_threat_score(user_id)

    async def get_security_report(self) -> SecurityReport:
        """Generate a comprehensive security report.

        Returns:
            SecurityReport with current security status.
        """
        # Active threats
        active = self._threat_monitor.get_active_threats()
        threat_breakdown: dict[str, int] = {}
        for threat in active:
            level_key = threat.level.value
            threat_breakdown[level_key] = threat_breakdown.get(level_key, 0) + 1

        # Open incidents
        open_incidents = self._incidents.get_open_incidents()

        # Recent threats (last 10)
        recent_threats: list[dict[str, Any]] = [
            {
                "id": t.threat_id,
                "level": t.level.value,
                "type": t.threat_type,
                "description": t.description,
                "user_id": t.user_id,
                "detected_at": t.detected_at.isoformat(),
                "event_count": t.event_count,
            }
            for t in active[:10]
        ]

        # Recent incidents (last 10)
        recent_history = self._incidents.get_incident_history(limit=10)
        recent_incidents: list[dict[str, Any]] = [
            {
                "id": i.incident_id,
                "severity": i.severity.value,
                "status": i.status.value,
                "title": i.title,
                "detected_at": i.detected_at.isoformat(),
            }
            for i in recent_history
        ]

        # Recommendations
        recommendations: list[str] = []
        critical_count = threat_breakdown.get("critical", 0)
        high_count = threat_breakdown.get("high", 0)

        if critical_count > 0:
            recommendations.append(
                f"{critical_count} CRITICAL threats active -- immediate review required"
            )
        if high_count > 0:
            recommendations.append(
                f"{high_count} HIGH threats active -- review within 1 hour"
            )
        if self._mode == TRONMode.OBSERVE and len(active) > 5:
            recommendations.append(
                "Consider upgrading TRON mode to SUGGEST_AUTO_LOW "
                "for automatic low-threat handling"
            )

        return SecurityReport(
            generated_at=datetime.now(UTC),
            mode=self._mode.value,
            active_threats=len(active),
            threat_breakdown=threat_breakdown,
            open_incidents=len(open_incidents),
            compliance_status="unknown",  # Set after compliance audit
            recent_threats=recent_threats,
            recent_incidents=recent_incidents,
            recommendations=recommendations,
        )
